/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.fon.silab.spring.springdata.jasper.forms;

import rs.fon.silab.spring.springdata.jasper.controller.JasperController;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import rs.fon.silab.spring.springdata.domen.Mesto;

/**
 *
 * @author filip
 */
public class FrmMesta extends javax.swing.JDialog {

    private Map<String, Object> map;

    /**
     * Creates new form FrmMesta
     */
    public FrmMesta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        map = new HashMap<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jasper reports - mesto");

        jButton1.setText("Get All Places");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JasperController jc = JasperController.getInstance();
        List<Mesto> lm = new LinkedList<Mesto>();
        lm = jc.getAllMesta();
        fillMap(lm, map);

        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport("MestaA4.jasper", map);
            JasperViewer viewer = new JasperViewer(jasperPrint);
            viewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(FrmMesta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    private void fillMap(List<Mesto> lm, Map<String, Object> map) {
        for (Mesto mesto : lm) {
            map.put(Integer.toString(mesto.getPtt()), map);
        }
    }
}
